# Generated by Django 4.2.7 on 2024-06-15 00:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_exam_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Profile',
        ),
    ]
